name: midgard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  date_picker_plus: ^3.0.0
  file_picker: ^6.1.1
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.20.3
  highlight: ^0.7.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.1.0
  http_parser: ^4.0.2
  json_annotation: ^4.0.1
  logger: ^1.1.0
  markdown_editor_plus: ^0.2.13
  multi_value_listenable_builder: ^0.0.2
  path_provider: ^2.0.2
  redacted: ^1.0.11
  responsive_builder: ^0.7.0
  rive: ^0.12.3
  sidebarx: ^0.16.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  universal_html: ^2.2.4
  url_strategy: ^0.2.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

#dependency_overrides:
#  web: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/

