import 'package:flutter/material.dart';

const Color kcPrimaryColor = Color(0xFF9600FF);
const Color kcPrimaryColorDark = Color(0xFF300151);
const Color kcDarkBlue = Color(0xFF0F0F3F);
const Color kcBlack = Color(0xFF000000);
const Color kcRed = Color(0xFFE50914);
const Color kcDarkGreyColor = Color(0xFF1A1B1E);
const Color kcMediumGrey = Color(0xFF474A54);
const Color kcLightGrey = Color.fromARGB(255, 187, 187, 187);
const Color kcVeryLightGrey = Color(0xFFE3E3E3);
const Color kcWhite = Color(0xFFFFFFFF);
const Color kcBackgroundColor = kcDarkGreyColor;
const Color kcBearBackgroundColor = Color.fromARGB(255, 249, 246, 254);
const Color kcAdminBadgeColor = Colors.redAccent;
const Color kcProposerBadgeColor = Colors.greenAccent;
const Color kcUserBadgeColor = Colors.blueAccent;
const Color kcOrange = Color(0xFFFFA500);
const Color kcGreen = Color(0xFF008000);
const Color kcBlue = Color(0xFF0000FF);
const Color kcBlueAccent = Colors.lightBlueAccent;
const Color kcEasyBadgeColor = Colors.tealAccent;
const Color kcMediumBadgeColor = Colors.orangeAccent;
const Color kcHardBadgeColor = Colors.redAccent;
const Color kcOlympiadBadgeColor = Colors.purpleAccent;
const Color kcStandardIoBadgeColor = Colors.greenAccent;
const Color kcFileIoBadgeColor = Colors.deepOrangeAccent;
const Color kcOrangeAccent = Colors.orangeAccent;
